fail_fast: false
minimum_prek_version: "0.3.3"
default_install_hook_types: [ pre-push, commit-msg, pre-commit ]
exclude: |
  (?x)^(
    .release-please-manifest.json
  )

repos:
  - repo: meta
    hooks:
      - id: identity
        name: Print checked files
        description: Print input to the static check hooks for troubleshooting
      - id: check-hooks-apply
        name: Check if all hooks apply to the repository

  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ --maxkb=100 ]

  - repo: local
    hooks:
      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        types: [ python ]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        types: [ python ]

      - id: local-ty-check
        name: ty check
        entry: uv run ty check . --ignore unresolved-import
        language: unsupported
        types: [ python ]

      - id: local-commitizen
        name: commitizen check
        entry: uv run cz check --allow-abort --commit-msg-file
        language: unsupported
        stages: [ commit-msg ]

      - id: local-commitizen-branch
        name: commitizen branch check
        entry: uv run cz check --rev-range origin/HEAD..HEAD
        language: unsupported
        pass_filenames: false
        always_run: true
        stages:
          - pre-push

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
